const expertsActionTypes = {
  START_FETCH_EXPERTS: "START_FETCH_EXPERTS",
  FETCH_EXPERTS_SUCCESS: "FETCH_EXPERTS_SUCCESS",
  FETCH_EXPERTS_FAILURE: "FETCH_EXPERTS_FAILURE"
};

export default expertsActionTypes;
