const postsActionTypes = {
  START_CREATE_POST: "START_CREATE_POST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
  OPEN_POST_START: "OPEN_POST_START",
  OPEN_POST_SUCCESS: "OPEN_POST_SUCCESS",
  OPEN_POST_FAILURE: "OPEN_POST_FAILURE",
  REPLY_CREATE_START: "REPLY_CREATE_START",
  REPLY_CREATE_SUCCESS: "REPLY_CREATE_SUCCESS",
  REPLY_CREATE_FAILURE: "REPLY_CREATE_FAILURE"
};

export default postsActionTypes;
