const postsActionTypes = {
  START_CREATE_POST: "START_CREATE_POST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
  OPEN_POST_START: "OPEN_POST_START",
  OPEN_POST_SUCCESS: "OPEN_POST_SUCCESS",
  OPEN_POST_FAILURE: "OPEN_POST_FAILURE",
  FETCH_POSTS_START: "FETCH_POSTS_START",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_USER_POSTS_START: "FETCH_USER_POSTS_START",
  FETCH_USER_POSTS_SUCCESS: "FETCH_USER_POSTS_SUCCESS",
  FETCH_USER_POSTS_FAILURE: "FETCH_USER_POSTS_FAILURE",
  REPLY_CREATE_START: "REPLY_CREATE_START",
  REPLY_CREATE_SUCCESS: "REPLY_CREATE_SUCCESS",
  REPLY_CREATE_FAILURE: "REPLY_CREATE_FAILURE",
  REPLY_FETCH_START: "REPLY_FETCH_START",
  REPLY_FETCH_SUCCESS: "REPLY_FETCH_SUCCESS",
  REPLY_FETCH_FAILURE: "REPLY_FETCH_FAILURE"
};

export default postsActionTypes;
