const topicActionTypes = {
  TOGGLE_TOPIC_DROPDOWN: "TOGGLE_TOPIC_DROPDOWN",
  SET_CURRENT_TOPIC: "SET_CURRENT_TOPIC",
  START_FETCH_TOPICS: "START_FETCH_TOPICS",
  FETCH_TOPICS_SUCCESS: "FETCH_TOPICS_SUCCESS",
  FETCH_TOPICS_FAILURE: "FETCH_TOPICS_FAILURE"
};

export default topicActionTypes;
