const RepliesActionTypes = {
  START_CREATE_REPLY: "START_CREATE_REPLY",
  CREATE_REPLY_SUCCESS: "CREATE_REPLY_SUCCESS",
  CREATE_REPLY_FAILURE: "CREATE_REPLY_FAILURE",

  FETCH_REPLY_START: "FETCH_REPLY_START",
  FETCH_REPLY_SUCCESS: "FETCH_REPLY_SUCCESS",
  FETCH_REPLY_FAILURE: "FETCH_REPLY_FAILURE",
};

export default RepliesActionTypes;
