const userActionTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESSFULL",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  TOGGLE_REGISTRATION_MODAL: "TOGGLE_REGISTRATION_MODAL",
  TOGGLE_ACCOUNT_DROPDOWN: "TOGGLE_ACCOUNT_DROPDOWN",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE"
};

export default userActionTypes;
